#version: '3.8' # 도커 컴포즈 파일 형식의 버전을 지정합니다.

services:
  # 1. 프론트엔드 서비스
  react-app:
    build: ./model-front               # GitHub Actions가 빌드할 소스코드 폴더 경로
    image: taehyun05/react-app:latest   # 👈 추가: 빌드가 끝나면 도커 허브에 이 이름으로 저장하라는 뜻
    ports:
      - "80:80"
    restart: always

  # 2. 메인 자바 백엔드 서비스
  spring-app:
    build: ./model-api/app             # GitHub Actions가 빌드할 소스코드 폴더 경로
    image: taehyun05/spring-app:latest  # 👈 추가: 빌드가 끝나면 도커 허브에 이 이름으로 저장하라는 뜻
    ports:
      - "8080:8080"
    restart: always

  # 3. 파이썬 AI/데이터 백엔드 서비스
  fastapi-app:
    build: ./model_test/model_app      # GitHub Actions가 빌드할 소스코드 폴더 경로
    image: taehyun05/fastapi-app:latest # 👈 추가: 빌드가 끝나면 도커 허브에 이 이름으로 저장하라는 뜻
    ports:
      - "8000:8000"
    restart: always