services:
  # 1. 프론트엔드 서비스
  react-app:
    build: ./model-front
    image: taehyun05/react-app:latest
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - container-spring
      - fastapi-app
    restart: unless-stopped

  # 2. 메인 자바 백엔드 서비스
  container-spring:
    build: ./model-api/app
    image: taehyun05/test:model_app-spring-app
    container_name: container-spring
    ports:
      - "8080:8080"
    restart: unless-stopped

  # 3. 파이썬 AI/데이터 백엔드 서비스
  fastapi-app:
    build: ./model_test/model_app
    image: taehyun05/test:model_app-fastapi-app
    container_name: container-fastapi-app
    ports:
      - "8000:8000"
    restart: unless-stopped